spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    listener:
      ack-mode: TIME
      ack-time: 500
    consumer:
      enable-auto-commit: false
      auto:
        commit:
          interval:
            ms: 500
      max-poll-records: 5
      auto-offset-reset: earliest
      # properties:
      #   ackMode: RECORD
      group-id: "myGroup"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max.poll.interval.ms: 2500
        spring:
          json:
            trusted:
              packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8081